# -*- coding: utf-8 -*-
"""EE016 Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14vOM8HQggtKVn0qzsELi2vDpgCDT1ClG

https://github.com/Rm4miner/EE-016-final-project
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sb
import random as rand

# Outputing Data Table
data_names = ['longitude', 'latitude', 'hosuing_median_age', 'total_rooms', 'total_bedrooms', 'population', 'households', 'median_income', 'median_house_value', 'ocean proximity']
data = pd.read_csv('/content/housing.csv', names = data_names)
data.head()

df = pd.read_csv("housing.csv")
df.shape

data.columns

numeric_cols = ['longitude', 'latitude', 'housing_median_age', 'total_rooms',
                'total_bedrooms', 'population', 'households', 'median_income',
                'median_house_value']

data[numeric_cols] = data[numeric_cols].apply(pd.to_numeric, errors='coerce')

data.describe()

from sklearn.preprocessing import LabelEncoder, StandardScaler

# Encode categorical columns
for col in df.select_dtypes(include='object'):
    df[col] = LabelEncoder().fit_transform(df[col])

# Feature scaling
scaler = StandardScaler()
numeric_cols = df.select_dtypes(include=np.number).columns
df[numeric_cols] = scaler.fit_transform(df[numeric_cols])